// Array de objetos representando espécies animais brasileiras, com foco em espécies ameaçadas.
// Cada objeto contém informações sobre o nome científico, nome popular, características, região, status de conservação, causas de ameaça e um link para a Wikipédia.

let dados = [
    // ... (dados das espécies)
    {
        nomeCientifico: "Cyanopsitta spixii",
        nomePopular: "Ararinha-azul",
        caracteristicas: "Pequena arara com plumagem azul vibrante, endêmica do Nordeste brasileiro. Extinta na natureza, mas em processo de reintrodução. Mede cerca de 50 cm de comprimento e pode viver até 30 anos.  Dieta: Frutos, sementes e nozes. Comportamento: Social e altamente inteligente, vive em pequenos grupos e imita sons.",
        regiao: "Caatinga",
        emRiscoDeExtincao: true,
        causasAmeaca: "Caça ilegal, tráfico de animais, perda de habitat",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Ararinha-azul",
        tags: "aves ave arara pássaro pássaros",
    },
    {
        nomeCientifico: "Pteronura brasiliensis",
        nomePopular: "Ariranha",
        caracteristicas: "Maior mustelídeo do mundo, com pelagem castanho-escura e focinho comprido. Vive em grupos familiares e habita rios e igarapés da Amazônia. Pode pesar até 30 kg. Dieta: Peixes, crustáceos e pequenos mamíferos aquáticos. Comportamento: Social, costuma viver em grupos e é conhecido por sua habilidade de caça em equipe.",
        regiao: "Amazônia",
        emRiscoDeExtincao: true,
        causasAmeaca: "Poluição da água, destruição de habitat, caça",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Ariranha",
        tags: "mamífero mamíferos ariranha lontra mustelídeo",
    },
    {
        nomeCientifico: "Panthera onca",
        nomePopular: "Onça-pintada",
        caracteristicas: "Maior felino das Américas, com padrão de pelagem único. Pode pesar entre 56 a 96 kg e medir 1,5 a 2,7 metros de comprimento, incluindo a cauda. Dieta: Carnívora, alimenta-se de diferentes presas, como capivaras e cervos. Comportamento: Solitária, territorial e excelente nadadora.",
        regiao: "Amazônia, Pantanal, Cerrado",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça",
        linkWikipedia: "https://pt.wikipedia.org/wiki/On%C3%A7a-pintada",
        tags: "mamífero mamíferos felino onça onça-pintada",
    },
    {
        nomeCientifico: "Inia geoffrensis",
        nomePopular: "Boto cor-de-rosa",
        caracteristicas: "Cetáceo de água doce com coloração característica que varia do cinza ao rosa. Pode atingir até 2,5 metros de comprimento. Dieta: Peixes, crustáceos e outros animais aquáticos. Comportamento: Sociável e curioso, frequentemente visto sozinho ou em pequenos grupos.",
        regiao: "Amazônia",
        emRiscoDeExtincao: true,
        causasAmeaca: "Poluição da água, pesca incidental, construção de hidrelétricas",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Boto_cor-de-rosa",
        tags: "mamífero mamíferos cetáceo boto golfinho",
    },
    {
        nomeCientifico: "Anodorhynchus hyacinthinus",
        nomePopular: "Arara-azul",
        caracteristicas: "Ave de grande porte com plumagem azul vibrante. Mede cerca de 100 cm de comprimento e pode viver mais de 60 anos. Dieta: Sementes, nozes, e frutas. Comportamento: Social, costuma viver em pares ou grupos, e é uma excelente voadora.",
        regiao: "Pantanal",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, tráfico de animais, captura para o comércio ilegal de aves",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Arara-azul",
        tags: "aves ave arara pássaro pássaros",
    },
    {
        nomeCientifico: "Leontopithecus rosalia",
        nomePopular: "Mico-leão-dourado",
        caracteristicas: "Pequeno primata com pelagem dourada, endêmico da Mata Atlântica. Mede cerca de 25 a 35 cm de comprimento. Dieta: Frutas, insetos e pequenos vertebrados. Comportamento: Social, vive em grupos familiares e é conhecido por suas vocalizações.",
        regiao: "Mata Atlântica",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, fragmentação de habitat, captura para o tráfico de animais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Mico-le%C3%A3o-dourado",
        tags: "mamífero mamíferos primata mico macaco",
    },
    {
        nomeCientifico: "Hydrochoerus hydrochaeris",
        nomePopular: "Capivara",
        caracteristicas: "Maior roedor do mundo, herbívoro, pode pesar até 65 kg e medir até 1,3 metros de comprimento. Dieta: Gramas, plantas aquáticas e cascas de árvores. Comportamento: Social, vive em grupos, e é semi-aquático.",
        regiao: "Pantanal",
        emRiscoDeExtincao: true,
        causasAmeaca: "Destruição de habitat, caça, mudanças climáticas",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Capivara",
        tags: "mamífero mamíferos roedor capivara roedores",
    },
    {
        nomeCientifico: "Tapirus terrestris",
        nomePopular: "Anta",
        caracteristicas: "Maior mamífero terrestre da América do Sul, com peso que pode chegar a 300 kg e comprimento de até 2,5 metros. Dieta: Herbívora, alimenta-se de folhas, brotos e frutas. Comportamento: Solitária, é um excelente nadador e importante dispersor de sementes.",
        regiao: "Amazônia, Pantanal, Mata Atlântica",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, atropelamentos",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Anta",
        tags: "mamífero mamíferos anta tapires",
    },
    {
        nomeCientifico: "Brachyteles arachnoides",
        nomePopular: "Macaco-aranha-de-cara-preta",
        caracteristicas: "Primata de grande porte, com cauda preênsil e habilidade de se locomover entre as árvores. Endêmico da Mata Atlântica. Mede cerca de 50 a 70 cm e possui cauda longa. Dieta: Frutas, folhas e flores. Comportamento: Social, vive em grupos e é conhecido por suas acrobacias nas árvores.",
        regiao: "Mata Atlântica",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, fragmentação de habitat, caça",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Macaco-aranha-de-cara-preta",
        tags: "mamífero mamíferos primata macaco",
    },
    {
        nomeCientifico: "Guaruba guarouba",
        nomePopular: "Ararajuba",
        caracteristicas: "Ave de plumagem verde e amarela vibrante, endêmica da Amazônia. Mede cerca de 50 cm de comprimento e tem uma expectativa de vida de até 50 anos. Dieta: Frutos, sementes e flores. Comportamento: Social, vive em pequenos grupos e é conhecida por suas vocalizações interessantes.",
        regiao: "Amazônia",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, captura para o tráfico de animais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Ararajuba",
        tags: "aves ave arara pássaro pássaros",
    },
    {
        nomeCientifico: "Trichechus inunguis",
        nomePopular: "Peixe-boi-amazônico",
        caracteristicas: "Grande mamífero aquático herbívoro, adaptado à vida nos rios da Amazônia. Pode medir até 3 metros de comprimento e pesar mais de 400 kg. Dieta: Plantas aquáticas, algas e gramíneas. Comportamento: Sociável e curioso, muitas vezes visto em grupos familiares.",
        regiao: "Amazônia",
        emRiscoDeExtincao: true,
        causasAmeaca: "Poluição da água, colisões com embarcações, perda de habitat",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Peixe-boi-amaz%C3%B4nico",
        tags: "mamífero mamíferos aquático peixe-boi",
    },
    {
        nomeCientifico: "Chlamyphorus truncatus",
        nomePopular: "Bola-de-ferro",
        caracteristicas: "Menor tatu do mundo, com carapaça óssea rígida e hábitos subterrâneos. Endêmico do Pampa. Mede cerca de 20 cm de comprimento. Dieta: Invertebrados, como formigas e cupins. Comportamento: Solitário, passará a maior parte do tempo em buracos cavados no solo.",
        regiao: "Pampa",
        emRiscoDeExtincao: true,
        causasAmeaca: "Perda de habitat, agricultura, caça",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Bola-de-ferro",
        tags: "mamífero mamíferos tatu bola-de-ferro",
    },
    {
        nomeCientifico: "Crax blumenbachii",
        nomePopular: "Mutum-de-ouroprete",
        caracteristicas: "Ave de grande porte, com plumagem negra brilhante e topete em formato de coroa. Endêmico da Mata Atlântica. Mede cerca de 80 cm de comprimento. Dieta: Frutas, sementes, invertebrados. Comportamento: Solitário ou em pares, principalmente visto no solo.",
        regiao: "Mata Atlântica",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, captura para o tráfico de animais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Mutum-de-ouroprete",
        tags: "aves ave mutum pássaro pássaros",
    },
    {
        nomeCientifico: "Myrmecophaga tridactyla",
        nomePopular: "Tamanduá-bandeira",
        caracteristicas: "Mamífero de grande porte, com pelagem longa e densa, focinho alongado e língua comprida adaptada para capturar insetos. Pode medir até 2 metros de comprimento, incluindo a cauda. Dieta: Formigas e cupins. Comportamento: Solitário e noturno, possui grande capacidade de cavar.",
        regiao: "Cerrado, Pantanal",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, atropelamentos, incêndios florestais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Tamandu%C3%A1-bandeira",
        tags: "mamífero mamíferos tamanduá bandeira",
    },
    {
        nomeCientifico: "Ozotoceros bezoarticus",
        nomePopular: "Veado-campeiro",
        caracteristicas: "Mamífero herbívoro de porte médio, com pelagem marrom clara e patas finas. Pode pesar até 30 kg e medir cerca de 1,2 metros de comprimento. Dieta: Gramíneas e ervas. Comportamento: Geralmente solitário ou em pequenos grupos, é ágil e veloz, adaptado a campos abertos.",
        regiao: "Cerrado, Pantanal, Pampa",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, fragmentação de habitat, incêndios florestais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Veado-campeiro",
        tags: "mamífero mamíferos veado cervo",
    },
    {
        nomeCientifico: "Alouatta caraya",
        nomePopular: "Bugio-preto",
        caracteristicas: "Primata de médio porte com pelagem negra nos machos e marrom-alaranjada nas fêmeas. Conhecido por seus sons altos e distintivos que podem ser ouvidos a quilômetros de distância. Dieta: Folhas, frutas e flores. Comportamento: Arborícola e territorial, vive em grupos familiares.",
        regiao: "Cerrado, Pantanal",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, incêndios florestais, caça",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Bugio-preto",
        tags: "mamífero mamíferos primata bugio",
    },
    {
        nomeCientifico: "Lutreolina crassicaudata",
        nomePopular: "Cuíca-d’água",
        caracteristicas: "Marsupial de pequeno porte com pelagem densa e cauda preênsil. Vive próximo a corpos d’água e tem hábitos noturnos. Dieta: Insetos, pequenos vertebrados e frutas. Comportamento: Solitário e territorial, constrói ninhos em buracos no solo.",
        regiao: "Pantanal, Cerrado",
        emRiscoDeExtincao: true,
        causasAmeaca: "Destruição de habitat, incêndios florestais, predação por animais domésticos",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Cu%C3%ADca-d%27%C3%A1gua",
        tags: "mamífero mamíferos marsupial cuíca",
    },
    {
        nomeCientifico: "Rhea americana",
        nomePopular: "Ema",
        caracteristicas: "Ave grande, não voadora, de plumagem acinzentada e pernas longas, que pode atingir até 1,5 metros de altura. Dieta: Onívora, alimenta-se de plantas, insetos, e pequenos vertebrados. Comportamento: Vive em grupos durante a maior parte do ano e é conhecida por seus comportamentos de cuidado parental, com o macho cuidando dos ovos e filhotes.",
        regiao: "Cerrado, Pantanal",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, incêndios florestais, agricultura intensiva",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Ema",
        tags: "ave aves ema pássaro pássaros",
    },
    {
        nomeCientifico: "Priodontes maximus",
        nomePopular: "Tatu-canastra",
        caracteristicas: "Maior espécie de tatu, podendo medir até 1,5 metros de comprimento. Tem uma carapaça segmentada e garras poderosas para cavar. Dieta: Insetos, principalmente formigas e cupins. Comportamento: Solitário e de hábitos noturnos, constrói tocas profundas no solo.",
        regiao: "Cerrado, Pantanal, Amazônia",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, incêndios florestais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Tatu-canastra",
        tags: "mamífero mamíferos tatu canastra",
    },
    {
        nomeCientifico: "Herpailurus yagouaroundi",
        nomePopular: "Gato-mourisco",
        caracteristicas: "Felino de pequeno a médio porte, com pelagem uniforme que varia do cinza ao marrom escuro. Pode pesar até 9 kg e mede cerca de 60 cm de comprimento. Dieta: Pequenos vertebrados, como roedores e aves. Comportamento: Solitário e crepuscular, é ágil e prefere áreas de vegetação densa.",
        regiao: "Cerrado, Mata Atlântica, Amazônia",
        emRiscoDeExtincao: true,
        causasAmeaca: "Desmatamento, caça, incêndios florestais",
        linkWikipedia: "https://pt.wikipedia.org/wiki/Gato-mourisco",
        tags: "mamífero mamíferos felino gato",
    },
    
];